config/routes.rb
Lunchify::Application.routes.draw do
  resources :users

  resources :votes

  

  resources :food_items
  resources :menu_items
  resources :menus
end

app/models/food_item.rb
class FoodItem < ActiveRecord::Base
has_many :menu_item
has_many :menus, through: :menu_items

validates :name, uniqueness: true, presence: true
validates :description, uniqueness: true, presence: true

end

app/models/menu.rb
class Menu < ActiveRecord::Base
  has_many :menu_items
  has_many :food_items, through: :menu_items

  validates :day, uniqueness: true, presence: true
end

app/models/menu_item.rb
class MenuItem < ActiveRecord::Base
  belongs_to :menu
  belongs_to :food_item

  belongs_to :vote

  validates :food_item_id, presence: true
  validates :menu_id, presence: true

  def num_votes
    return self.vote
  end
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  has_many :menu_items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  require 'date'
end

app/controllers/food_items_controller.rb
class FoodItemsController < ApplicationController
  def new
    @food_item = FoodItem.new
  end

  def index
    @food_items = FoodItem.all
  end

  def create
    @food_item = FoodItem.new(food_item_params)
    if @food_item.save
      flash[:success] = "Thank you for submitting the Food Item!"      
      redirect_to food_items_path
    else
      flash[:danger] = "Whoops! You've made an error while creating a Food Item."
      render action: :new
    end
  end

  def edit
    @food_item = FoodItem.find(params[:id])
  end

  def update
    @food_item = FoodItem.find(params[:id])
    if @food_item.update_attributes(food_item_params)
      flash[:success] = "Your food_item was updated."
      redirect_to food_items_path
    else
      flash[:danger] = "Please check the errors in your update."
      render 'edit'
    end
  end

  def destroy
    @food_item_to_delete = FoodItem.find(params[:id])
      @food_item_to_delete.destroy
      flash[:success] = "Food Item destroyed."
      redirect_to food_items_path
  end

  private

  def food_item_params
    params.require(:food_item).permit(:name, :description)
  end
end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController

  def new
    @menu_item = MenuItem.new
  end

  def index
    @menu_items = MenuItem.all
  end

  def create
    @menu_item = MenuItem.new(menu_item_params)
    @vote = Vote.new
    @vote.save
    @menu_item.vote_id = @vote.id
    @menu_item.save
    redirect_to menus_path
  end

  def edit
    @menu_item = MenuItem.find(params[:id])
  end

  def votes
    vote = Vote.new(value: params[:value], menu_item_id: params[:id])
    if vote.save
      redirect_to :back, notice: "Thank you for voting."
    else
      redirect_to :back, alert: "Unable to vote, perhaps you already did."
    end
  end

  private

  def menu_item_params
    params.require(:menu_item).permit(:food_item_id, :menu_id)
  end
  
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController

  def new
    @menu = Menu.new
  end

  def index
    @menus = Menu.all
  end

  def create
    menu_params[:day] = Date.parse(menu_params[:day])
    @menu = Menu.new(menu_params)
    @menu.save
    redirect_to menus_path
  end

  def edit
    @menu = Menu.find(params[:id])
  end

  private

  def menu_params
    params.require(:menu).permit(:day)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def new
    # @vote = Vote.new
  end

  def create
    @vote = Vote.new
    @vote.save
    redirect_to menus_path
  end

  def vote_params
    params.require(:vote).permit()
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/food_item_helper.rb
module FoodItemHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/menu_item_helper.rb
module MenuItemHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/food_items/_food_item.html.erb
<table class="table table-hover">
  <%# menu.food_items.each do |food_item| %>
    
  <tr >
    <td><h3><%= food_item.name %></h3></td>
    <td>Votes: <%= food_item.menu_item.num_votes %></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td><%= food_item.description %></td>
  </tr>
 
    
  <%# end %>
</table> 

app/views/food_items/_form.html.erb
<%= form_for(@food_item) do |f| %>
<div class="form">

  <%= render 'error_messages' %>
    <div class="form-group">
      <%= f.text_field :name, {placeholder: "Food Item", class:"form-control"} %>
    </div>
    <div class="form-group">
      <%= f.text_area(:description, {rows: 6, placeholder: "Description", class:"form-control"}) %>
    </div>

    <br>
    <%= f.submit "Submit" , class: "btn btn-primary" %>
   
  <% end %>

</div>

app/views/food_items/edit.html.erb
<h1>Edit Food Item</h1>

<%= render 'form' %>
<br>
<br>

<%= link_to 'Back', food_items_path, :class=> "btn" %>

app/views/food_items/index.html.erb
<h1>Food Items</h1>



<br>
<table class="table table-hover">
  <% @food_items.each do |food_item| %>
    

  <tr >
    <td><h3><%= food_item.name %></h3></td>
  </tr>
  <tr>
    <td><%= food_item.description %></td>
  </tr>
 
    
<% end %>
</table> 

app/views/food_items/new.html.erb
<h2 class="form">Create Food Item</h2><br />
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lunchify</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
    <div class="header">
      <ul class="nav nav-pills pull-right">    

        <li class="<%= 'active' if current_page?(menus_path) %>"><%= link_to 'Menus', menus_path %></li>
        <li class="<%= 'active' if current_page?(new_food_item_path) %>"><%= link_to 'Add Food', new_food_item_path %></li>
        <li class="<%= 'active' if current_page?(new_menu_item_path) %>"><%= link_to 'Add Menu Item', new_menu_item_path %></li>
        <li class="<%= 'active' if current_page?(new_menu_path) %>"><%= link_to 'Add Menu', new_menu_path %></li>
      </ul>
      <%= link_to image_tag("lunchify.png"), menus_path %>
    </div>
    <% flash.each do |key, value| %>
    <%= content_tag(:div, "#{value}<button type='button' class='close' data-dismiss='alert' aria-hidden='true'>&times;</button>".html_safe, class: "alert alert-#{key} container alert-dismissable") %>    
    <% end %>
    
    <%= yield %>

    <div class="footer">
      <p>&copy; Created Tyler Sangster for Shopify 2013</p>
    </div>
    
    </div> <!-- /container -->
  

  </body>
</html>

app/views/menu_items/_form.html.erb
<%= form_for(@menu_item) do |f| %>
  <div>
    <div><%= f.label :food_item %></div>
    <div><%= collection_select(:menu_item, :food_item_id, FoodItem.all, :id, :name, {:prompt=>true}) %></div>
  </div>
  <div>
    <div><%= f.label :menu %></div>
    <div><%= collection_select(:menu_item, :menu_id, Menu.all, :id, :day, {:prompt=>true}) %></div>
  </div>
<br>

<%= f.submit "Submit" , class: "btn btn-primary" %>

<% end %>

app/views/menu_items/index.html.erb
<h1>Menu Items</h1>



<br>
<table class="table table-hover">
  <% @menu_items.each do |menu_item| %>
    

  <tr >
    <td><h3><%= menu_item.name %></h3></td>
  </tr>
  <tr>
    <td><%= menu_item.description %></td>
  </tr>
 
    
<% end %>
</table> 

app/views/menu_items/new.html.erb
<h1>New Menu Item</h1>

<%= render 'form' %>
<br>

app/views/menus/_food_item.html.erb
<table class="table table-hover">
  <% food_items.each do |food_item| %>
    
  <tr >
    
    <td><h3><%= food_item.name %></h3></td>
    <td>Votes: <%= food_item.menu_item.votes %></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td><%= food_item.description %></td>
  </tr>
 
    
  <% end %>
</table> 

app/views/menus/_form.html.erb
<%= form_for(@menu) do |f| %>
  <div>
    <div><%= f.label :day %></div>
    <!-- <input type="text" data-behaviour='datepicker' > -->
  

    <div><%#= f.text_field :day, :id => "datepicker"   %></div>

    <%= f.text_field :day, :id => "datepicker", :value => Date.today %>
<script>
$('#datepicker').datepicker({format: 'yyyy-mm-dd'});
</script>
  </div>

  <br>
  <%= f.submit "Submit" , class: "btn btn-primary" %>
 
<% end %>

app/views/menus/_menu.html.erb
<table class="table table-hover">
  <% menu.menu_items.each do |menu_item| %>
    
  <tr >
    
    <td><h3><%= menu_item.food_item.name %></h3></td>
    <td>Votes: <%= menu_item.vote.votes %></td>
    <td>

      <span class="glyphicon glyphicon-chevron-up"></span>
      <span class="glyphicon glyphicon-chevron-down"></span>

    </td>

  </tr>
  <tr>
    <td><%= menu_item.food_item.description %></td>
  </tr>
 
    
  <% end %>
</table> 

app/views/menus/index.html.erb
<% @menus.each do |menu| %>
  <h2><%= menu.day.strftime("%A %B %-d") %></h2>
  <div class="jumbotron">
    <%= render partial: "menu", locals: {menu: menu} %>
  </div>
<% end %>

app/views/menus/new.html.erb
<h1>Create new Menu</h1>

<%= render 'form' %>
<br>
<br>